spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gugumo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  data:
    web:
      pageable:
        one-indexed-parameters: true

  jwt:
    secret: 339c5f60d4b8c54ada6a66432d405a83d959f6306d0157e27a72dd90c06290f1
    expiration_time: 86400000   #1일