spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gugumo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace